import java.time.Month;
import java.time.Period;
import java.time.LocalDate;
import java.time.temporal.ChronoUnit;
import java.util.Locale;
import java.util.concurrent.TimeUnit;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author LucasPC
 */
public class TelaPrincipal extends javax.swing.JFrame {

    // Cria o Metódo da Tela Principal //
    public TelaPrincipal() {
        initComponents();
        comboTQuarto.setSelectedItem(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelNome = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        labelSobrenome = new javax.swing.JLabel();
        txtSobrenome = new javax.swing.JTextField();
        labelEndereco = new javax.swing.JLabel();
        txtEndereco = new javax.swing.JTextField();
        labelCep = new javax.swing.JLabel();
        txtCep = new javax.swing.JTextField();
        labelCelular = new javax.swing.JLabel();
        txtCelular = new javax.swing.JTextField();
        labelEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        labelNacionalidade = new javax.swing.JLabel();
        txtNacionalidade = new com.toedter.components.JLocaleChooser();
        labelCheckin = new javax.swing.JLabel();
        txtCheckin = new com.toedter.calendar.JDateChooser();
        txtDataN = new com.toedter.calendar.JDateChooser();
        labelDataN = new javax.swing.JLabel();
        labelGenero = new javax.swing.JLabel();
        txtGenero = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        labelCheckout = new javax.swing.JLabel();
        labelTipoQuarto = new javax.swing.JLabel();
        labelNumeroQuarto = new javax.swing.JLabel();
        txtCheckout = new com.toedter.calendar.JDateChooser();
        jPanel1 = new javax.swing.JPanel();
        buttonCalcular = new javax.swing.JButton();
        labelDiaria = new javax.swing.JLabel();
        labelVTotal = new javax.swing.JLabel();
        buttonSair = new javax.swing.JButton();
        buttonLimpar = new javax.swing.JButton();
        txtDiaria = new javax.swing.JTextField();
        txtVTotal = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        comboTQuarto = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        comboNumQuarto = new javax.swing.JComboBox<>();
        labelValidar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("simplyHotel - Tela de Cadastro");
        setBackground(new java.awt.Color(228, 226, 210));
        setResizable(false);

        labelNome.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelNome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/1.nome.png"))); // NOI18N
        labelNome.setText("Nome");

        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });

        labelSobrenome.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelSobrenome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/2.sobrenome.png"))); // NOI18N
        labelSobrenome.setText("Sobrenome");

        txtSobrenome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSobrenomeActionPerformed(evt);
            }
        });

        labelEndereco.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelEndereco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/3.endereco.png"))); // NOI18N
        labelEndereco.setText("Endereço");

        labelCep.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelCep.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/4.cep.png"))); // NOI18N
        labelCep.setText("CEP");

        labelCelular.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelCelular.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/5.telefone.png"))); // NOI18N
        labelCelular.setText("Celular");

        txtCelular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCelularActionPerformed(evt);
            }
        });
        txtCelular.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCelularKeyPressed(evt);
            }
        });

        labelEmail.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelEmail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/6.email.png"))); // NOI18N
        labelEmail.setText("E-mail");

        labelNacionalidade.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelNacionalidade.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/7.nacionalidade.png"))); // NOI18N
        labelNacionalidade.setText("Nacionalidade");

        txtNacionalidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNacionalidadeActionPerformed(evt);
            }
        });

        labelCheckin.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelCheckin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/10.checkin.png"))); // NOI18N
        labelCheckin.setText("Data Check-In");

        txtCheckin.setDateFormatString("dd/MM/yyyy");

        txtDataN.setDateFormatString("dd/MM/yyyy");

        labelDataN.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelDataN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/11.checkout.png"))); // NOI18N
        labelDataN.setText("Data de nascimento");

        labelGenero.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelGenero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/9.genero.png"))); // NOI18N
        labelGenero.setText("Gênero");

        txtGenero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Feminino", "Outros" }));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Sobrenome", "Endereço ", "CEP", "Celular", "E-mail", "Nacionalidade", "Data de Nascimento", "Gênero", "Check-In", "Check-Out", "Tipo de Quarto", "Num. Quarto", "Valor Total R$"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        labelCheckout.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelCheckout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/11.checkout.png"))); // NOI18N
        labelCheckout.setText("Data Check-Out");

        labelTipoQuarto.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelTipoQuarto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/12.tipoquarto.png"))); // NOI18N
        labelTipoQuarto.setText("Tipo de Quarto");

        labelNumeroQuarto.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelNumeroQuarto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/13.numero.png"))); // NOI18N
        labelNumeroQuarto.setText("Número do Quarto");

        txtCheckout.setDateFormatString("dd/MM/yyyy");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        buttonCalcular.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cadastrar.png"))); // NOI18N
        buttonCalcular.setText("Adicionar | Calcular");
        buttonCalcular.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCalcularActionPerformed(evt);
            }
        });

        labelDiaria.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelDiaria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/14.vdiaria.png"))); // NOI18N
        labelDiaria.setText("Valor Diária - R$");

        labelVTotal.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelVTotal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/15.vtotal.png"))); // NOI18N
        labelVTotal.setText("Valor Total - R$");

        buttonSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/sair.png"))); // NOI18N
        buttonSair.setText("Sair");
        buttonSair.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSairActionPerformed(evt);
            }
        });

        buttonLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/reset.png"))); // NOI18N
        buttonLimpar.setText("Limpar");
        buttonLimpar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLimparActionPerformed(evt);
            }
        });

        txtDiaria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDiariaActionPerformed(evt);
            }
        });

        txtVTotal.setEditable(false);
        txtVTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVTotalActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 9)); // NOI18N
        jLabel2.setText("© simplyHotel - Todos os direitos reservados");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labelDiaria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelVTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(85, 85, 85)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtDiaria, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtVTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addComponent(buttonCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90)
                .addComponent(buttonLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90)
                .addComponent(buttonSair, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(22, 22, 22))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelDiaria)
                            .addComponent(txtDiaria, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelVTotal)
                            .addComponent(txtVTotal, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)))
                    .addComponent(buttonSair, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonLimpar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonCalcular, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(3, 3, 3)
                .addComponent(jLabel2)
                .addContainerGap())
        );

        comboTQuarto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Individual", "Casal", "Familiar", "Presidencial" }));
        comboTQuarto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboTQuartoActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\LucasPC\\Desktop\\Imagens\\capa.png")); // NOI18N

        labelValidar.setFont(new java.awt.Font("Segoe UI", 0, 9)); // NOI18N
        labelValidar.setForeground(new java.awt.Color(204, 0, 0));
        labelValidar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labelNumeroQuarto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelTipoQuarto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelCheckout, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelCheckin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelDataN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelNacionalidade, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelCelular, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelCep, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelEndereco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelSobrenome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelNome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labelValidar, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtCelular)
                            .addComponent(txtCep)
                            .addComponent(txtNome)
                            .addComponent(txtSobrenome)
                            .addComponent(txtEndereco)
                            .addComponent(txtEmail)
                            .addComponent(txtNacionalidade, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addComponent(txtDataN, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                            .addComponent(txtGenero, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtCheckin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addComponent(txtCheckout, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                        .addComponent(comboTQuarto, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(comboNumQuarto, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(55, 55, 55)
                .addComponent(jScrollPane1))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelNome)
                                .addGap(18, 18, 18)
                                .addComponent(labelSobrenome)
                                .addGap(18, 18, 18)
                                .addComponent(labelEndereco)
                                .addGap(18, 18, 18)
                                .addComponent(labelCep)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(labelCelular)
                                    .addComponent(txtCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtSobrenome, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtCep, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelValidar, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelEmail)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelNacionalidade)
                            .addComponent(txtNacionalidade, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(labelDataN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtDataN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelGenero)
                            .addComponent(txtGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelCheckin)
                            .addComponent(txtCheckin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCheckout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelCheckout))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelTipoQuarto)
                            .addComponent(comboTQuarto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(comboNumQuarto)
                                .addGap(1, 1, 1))
                            .addComponent(labelNumeroQuarto))
                        .addGap(3, 3, 3))
                    .addComponent(jScrollPane1))
                .addGap(15, 15, 15)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCalcularActionPerformed
        
        
        // Faz o Cálculo do Dia do Check-In e Check-out e dá o Valor Total //
        
         try {  
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy", Locale.ENGLISH);
                        Date firstDate = txtCheckin.getDate();
                        Date secondDate = txtCheckout.getDate();

                        long diffInMillies = Math.abs(secondDate.getTime() - firstDate.getTime());
                        long diff = TimeUnit.DAYS.convert(diffInMillies, TimeUnit.MILLISECONDS);

                       txtVTotal.setText(String.valueOf(diff));
                       
                       int qtdDias = (int) diff;
                       int diaria = Integer.parseInt(txtDiaria.getText());
                       int valortotal = diaria * qtdDias;
                       txtVTotal.setText(Integer.toString(valortotal));

            } catch (Exception e) {
             e.printStackTrace();
            }
               

        if(txtNome.getText().equals("") || txtSobrenome.getText().equals("") || txtEndereco.getText().equals("") 
        || txtCep.getText().equals("") || txtCelular.getText().equals("") || txtEmail.getText().equals("") 
        || txtNacionalidade.getSelectedItem().equals(null) || txtDiaria.getText().equals("") || txtVTotal.getText().equals("")) {
        JOptionPane.showMessageDialog(this, "Por favor preencha todos os dados.");
         } else {
         
        // Preenche na tabela com os campos digitados //
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[] {    
        txtNome.getText(),
        txtSobrenome.getText(),
        txtEndereco.getText(),
        txtCep.getText(),
        txtCelular.getText(),
        txtEmail.getText(),
        txtNacionalidade.getSelectedItem(),
        txtDataN.getDate(),
        txtGenero.getSelectedItem(),
        txtCheckin.getDate(),
        txtCheckout.getDate(),
        comboTQuarto.getSelectedItem(),
        comboNumQuarto.getSelectedItem(),
        txtVTotal.getText() });
        
        }
    }//GEN-LAST:event_buttonCalcularActionPerformed

    
    private JFrame frame;
    private void buttonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSairActionPerformed
        
        // Cria a ação do botão sair //
        frame = new JFrame("Sair");
        
        if(JOptionPane.showConfirmDialog(frame, "Você realmente quer sair?", "Simply Hotel", 
                JOptionPane.YES_OPTION) == JOptionPane.YES_NO_OPTION) {
        System.exit(0);
    }
        
    }//GEN-LAST:event_buttonSairActionPerformed

    private void buttonLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLimparActionPerformed
       
        // Reseta todos os dados dos text's Fields e tabelas //
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        
        txtNome.setText(null);
        txtSobrenome.setText(null);
        txtEndereco.setText(null);
        txtCep.setText(null);
        txtCelular.setText(null);
        txtEmail.setText(null);
        txtNacionalidade.setSelectedIndex(0);
        txtDataN.setDate(null);
        txtGenero.setSelectedIndex(0);
        txtCheckin.setDate(null);
        txtCheckout.setDate(null);
        comboTQuarto.setSelectedIndex(0);
        comboNumQuarto.setSelectedItem(null);
        txtDiaria.setText(null);
        txtVTotal.setText(null);
        
    }//GEN-LAST:event_buttonLimparActionPerformed

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        
    }//GEN-LAST:event_txtNomeActionPerformed

    private void txtSobrenomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSobrenomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSobrenomeActionPerformed

    private void txtNacionalidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNacionalidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNacionalidadeActionPerformed

    private void txtDiariaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDiariaActionPerformed

    }//GEN-LAST:event_txtDiariaActionPerformed

    private void comboTQuartoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboTQuartoActionPerformed
       
        
        // Cria as opções de Número de Quarto quando o usuário escolher o Tipo //
        try {
        
        if(comboTQuarto.getSelectedItem().equals("Individual")) {
            comboNumQuarto.removeAllItems();
            txtDiaria.setText(String.valueOf(90));
            comboNumQuarto.addItem("101");
            comboNumQuarto.addItem("102");
            comboNumQuarto.addItem("103");
            comboNumQuarto.addItem("104");
            comboNumQuarto.addItem("105");      
            comboNumQuarto.setSelectedItem(null);
        } else if(comboTQuarto.getSelectedItem().equals("Casal")) {
            comboNumQuarto.removeAllItems();
            txtDiaria.setText(String.valueOf(120));
            comboNumQuarto.addItem("201");
            comboNumQuarto.addItem("202");
            comboNumQuarto.addItem("203");
            comboNumQuarto.addItem("204");
            comboNumQuarto.addItem("205");
            comboNumQuarto.setSelectedItem(null);
        } 
        else if(comboTQuarto.getSelectedItem().equals("Familiar")) {
            comboNumQuarto.removeAllItems();
            txtDiaria.setText(String.valueOf(180));
            comboNumQuarto.addItem("301");
            comboNumQuarto.addItem("302");
            comboNumQuarto.addItem("303");
            comboNumQuarto.addItem("304");
            comboNumQuarto.addItem("305");
            comboNumQuarto.setSelectedItem(null);
        } 
        else if(comboTQuarto.getSelectedItem().equals("Presidencial")) {
            comboNumQuarto.removeAllItems();
            txtDiaria.setText(String.valueOf(220));
            comboNumQuarto.addItem("401");
            comboNumQuarto.addItem("402");
            comboNumQuarto.addItem("403");
            comboNumQuarto.addItem("404");
            comboNumQuarto.addItem("405");
            comboNumQuarto.setSelectedItem(null);
    }
        } catch(Exception e) {
            System.out.println(e);
        }
        
        
    }//GEN-LAST:event_comboTQuartoActionPerformed

    private void txtVTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVTotalActionPerformed

    private void txtCelularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCelularActionPerformed

    }//GEN-LAST:event_txtCelularActionPerformed

    private void txtCelularKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCelularKeyPressed
        
        try {
            int ncelular = Integer.parseInt(txtCelular.getText());
            labelValidar.setText("");
        } catch(NumberFormatException e) {
            labelValidar.setText("Número inválido");
        }
        
    }//GEN-LAST:event_txtCelularKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCalcular;
    private javax.swing.JButton buttonLimpar;
    private javax.swing.JButton buttonSair;
    private javax.swing.JComboBox<String> comboNumQuarto;
    private javax.swing.JComboBox<String> comboTQuarto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel labelCelular;
    private javax.swing.JLabel labelCep;
    private javax.swing.JLabel labelCheckin;
    private javax.swing.JLabel labelCheckout;
    private javax.swing.JLabel labelDataN;
    private javax.swing.JLabel labelDiaria;
    private javax.swing.JLabel labelEmail;
    private javax.swing.JLabel labelEndereco;
    private javax.swing.JLabel labelGenero;
    private javax.swing.JLabel labelNacionalidade;
    private javax.swing.JLabel labelNome;
    private javax.swing.JLabel labelNumeroQuarto;
    private javax.swing.JLabel labelSobrenome;
    private javax.swing.JLabel labelTipoQuarto;
    private javax.swing.JLabel labelVTotal;
    private javax.swing.JLabel labelValidar;
    private javax.swing.JTextField txtCelular;
    private javax.swing.JTextField txtCep;
    private com.toedter.calendar.JDateChooser txtCheckin;
    private com.toedter.calendar.JDateChooser txtCheckout;
    private com.toedter.calendar.JDateChooser txtDataN;
    private javax.swing.JTextField txtDiaria;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEndereco;
    private javax.swing.JComboBox<String> txtGenero;
    private com.toedter.components.JLocaleChooser txtNacionalidade;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtSobrenome;
    private javax.swing.JTextField txtVTotal;
    // End of variables declaration//GEN-END:variables
}
